version: "3"
services:
    haproxy:
        build: ./loadbalancer
        container_name: haproxy
        ports:
             - "80:80"
        depends_on:
             - shop1
             - shop2

    shop1:
        build: ./webappshop
        container_name: shop1
        ports:
             - "8081:80"
        depends_on:
             - mssqldb

    shop2:
        build: ./webappshop 
        container_name: shop2
        ports:
             - "8082:80"
        depends_on:
             - mssqldb

    mssqldb:
        build: 
            context: ./sqlserver
            args: 
                - ACCEPT_EULA=${ACCEPT_EULA}
                - USER_ID=${USER_1}
                - SA_PASSWORD=${PASSWORD_1}
        env_file: 
            - .env
        container_name: mssqldb
        ports:
             - "1433:1433"